version: "2.3"
services:
  project:
    image: point_dg
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    runtime: nvidia
    ipc: host
    volumes:
      - ${PWD}/:/point_dg/workspace
      - ${DATA}:/point_dg/data